{% set name = "vega_datasets" %}
{% set version = "0.6.0" %}
{% set sha256 = "a38d25bcb9dbf06d4b8adfa25fc4fed19f329e3be4d9b55ebd1395574c2bf30b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas

test:
  imports:
    - vega_datasets
    - vega_datasets.tests

about:
  home: http://github.com/altair-viz/vega_datasets/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for offline access to Vega datasets"
  description: |
    A Python package for offline access to Vega datasets available at
    https://github.com/vega/vega-datasets.
    This package has several goals:
    - Provide straightforward access to the datasets in vega-datasets
    - return the results in the form of a Pandas dataframe.
    - wherever dataset size and/or license constraints make it possible,
      bundle the dataset with the package so that datasets can be loaded in
      the absence of a web connection.
  doc_url: http://github.com/altair-viz/vega_datasets/
  dev_url: http://github.com/altair-viz/vega_datasets/

extra:
  recipe-maintainers:
    - jakevdp
