travis:
  secure:
    BINSTAR_TOKEN: YMZw5nGQvFcZrs9cPVkINa7lo2zidZADzoKv7MVNNiW/enUHmNsSYbNnkowzZJz7HNyXEanltowLAMLnT7KSA50nbl5DAo3/jthrQac6lSbPNiDxbcbblpeMB8r+uJKqo/IohOOcYyVh1ghKFIwu3OTY9ZxTlWrMEHpPo/mJUBNsBIM8bBwwVlEa7OFKA77KpXjllFMTHBuekpTWumLg4m+4Q2ifkBJpPMKQA2K6BMtkF6MsNgc33KV4DFO9IRR/b1fnI7s40fmr+d/dnH0sH4vEmTQqccxeUKwsv82s/DZ9JSr5GcFgB814K4cmwa0GqPk+micWj0rOnFKf7GMdtlEW08acJtcN0ChQcOY1yT7IeXonNUPz30N1L5RStAfJS1IhHDJ6XgAHb6H5P5nHroXQYiG9/8YrOi1FPoP8+94ZNxoldbWdHnA03eVkP0OLM/cZTstywXcAIM3QEIN87B1SBSg9KdJrF5l7ctu1mMIB0y7SgsTZUspHdtWglXhLBd/+ZGJfjzaJobL1UuPPSt5NsogjhnjPQ4PqmWFlsc5Av5xqHp9Ab/bKE5v1JJPOK071HPZI2NDnAuWW9/gfjraVPX6RYWZ2aCB+fbPpzbfOizxXaXbdW27zOlR6Pp/V+jQeVjC/jq/lotDYPhkrgnrIPk8r1AonKkiayl8fa6A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
